// pages/Terms.js
import React from 'react';

const Terms = () => {
    return (
        <div className='relative left-40 top-48 w-[1280px]'>
            
            <p className='mb-4'>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sit amet ex sodales, viverra metus eu, dapibus felis. Quisque commodo, justo nec congue elementum, nulla ante tempor purus, nec euismod leo dolor fringilla mauris. Phasellus nec sem feugiat, commodo erat a, eleifend ante. Maecenas tempus dui eget massa eleifend, in vestibulum mi sollicitudin. Nunc orci massa, tincidunt et ultrices vitae, lobortis id metus. Suspendisse volutpat eget est ut laoreet. Sed est odio, volutpat ac pretium sed, venenatis vel mauris. Aliquam lorem felis, rutrum nec erat a, dapibus vehicula massa. Phasellus rutrum tincidunt vehicula. Quisque imperdiet diam volutpat risus volutpat pellentesque. Curabitur porta dignissim vulputate. Integer elementum lacus tristique quam cursus, placerat mollis erat bibendum. Aenean orci odio, viverra sed orci in, blandit malesuada arcu. Nullam pulvinar rutrum risus id imperdiet. Aenean cursus fermentum libero, a molestie ante molestie eget. Etiam mauris urna, malesuada sed augue ac, posuere auctor elit.</p>
            <p className='mb-4'>In luctus ac leo quis iaculis. Sed condimentum quam lectus, ac dignissim ante tincidunt sit amet. Sed id felis urna. Pellentesque eu consectetur ex. Quisque eu metus quis velit sollicitudin vestibulum in fringilla risus. Morbi consequat vel orci non dapibus. Nulla fringilla mattis cursus. Nulla sit amet erat ac odio dapibus volutpat. Phasellus efficitur convallis velit, quis fermentum lorem volutpat in.</p>
            <p className='mb-4'>Etiam vitae ligula ipsum. In quis risus euismod, facilisis orci non, aliquet ligula. Maecenas eu tortor non purus eleifend dapibus. Duis cursus et tortor eget scelerisque. Curabitur at blandit risus. Donec at ipsum quis enim vestibulum sodales. Proin maximus diam est, id molestie magna pellentesque sit amet. In eget neque justo. Cras pretium accumsan viverra.</p>
            <p className='mb-4'>Vestibulum pulvinar pulvinar venenatis. Nullam in lectus erat. Mauris et malesuada ligula. Proin aliquam mauris nec velit vestibulum accumsan. In ac convallis tellus, quis auctor odio. Nam scelerisque nibh et nisl finibus, at ultricies libero interdum. Duis vel tristique est. Pellentesque urna mi, fermentum vitae lacus vitae, laoreet interdum nisl. Aenean porttitor dolor augue, non varius risus venenatis at. Nullam sed aliquet quam. Nunc feugiat elit maximus efficitur elementum. Etiam dignissim orci in congue ultrices. Cras ipsum nisl, dictum ut malesuada vitae, ultrices vel velit.</p>
            <p className='mb-4'>Proin nec est convallis, dapibus orci at, pretium erat. Ut ac feugiat erat, eget sodales erat. Praesent tempor malesuada urna, in efficitur magna vehicula quis. Praesent fringilla leo a quam mattis, eget hendrerit metus luctus. Mauris quam neque, viverra in bibendum vel, suscipit vel urna. Integer maximus ornare risus nec tristique. Suspendisse sit amet nisl vulputate eros interdum viverra at vitae turpis. Duis quis nisl at justo imperdiet egestas. Sed cursus suscipit sodales. Donec a aliquet diam, ac pellentesque sapien. Nam interdum cursus dolor, nec pulvinar quam bibendum quis. Duis porttitor ante mauris, eu ornare sem tincidunt sed. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque sodales viverra mauris. Donec sed massa vel neque rutrum consectetur.</p>
            <p className='mb-4'>Praesent in orci id justo sagittis pretium. Vestibulum non est tempus, faucibus eros eget, porta leo. Donec eget sodales nisi. Pellentesque aliquet viverra tortor, nec congue nunc. Pellentesque hendrerit dui odio, eget rutrum ante laoreet sit amet. Nulla in mauris et nisl suscipit imperdiet. Proin eget mauris convallis, lobortis ipsum quis, placerat arcu. Praesent at diam vitae libero cursus dignissim. Maecenas condimentum commodo tristique.</p>
            <p className='mb-4'>Donec imperdiet purus in magna ullamcorper maximus. Fusce nec pellentesque diam. Proin dolor tortor, pharetra id elit ut, vehicula sodales lectus. Curabitur faucibus lorem at laoreet auctor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut ac ligula non mi fermentum sodales. Mauris efficitur et enim quis feugiat.</p>
            <p>Curabitur et finibus libero. Donec sit amet eros vitae dolor viverra imperdiet. Proin facilisis ultrices elit eu ornare. Nullam ut sapien quam. Suspendisse mattis mi euismod iaculis vehicula. Duis pellentesque pulvinar tellus nec efficitur. Aliquam in elit sed orci euismod molestie. Phasellus vitae odio eget quam tristique porta. Nulla nec viverra elit. Fusce mauris magna, vulputate fringilla mollis et, venenatis nec enim. Donec ornare, orci ac elementum dignissim, nisl sapien lobortis erat, id porta dolor turpis nec velit. Cras scelerisque convallis nulla, et interdum sem varius vitae.</p>
          
        </div>
    );
};

export default Terms;
